name = "WaveletsExt"
uuid = "8f464e1e-25db-479f-b0a5-b7680379e03f"
authors = ["Zeng Fung Liew <lzfliew@ucdavis.edu>", "Shozen Dan <shodan@ucdavis.edu>"]
version = "0.1.10"

[deps]
AverageShiftedHistograms = "77b51b56-6f8f-5c3a-9cb4-d71f9594ea6e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ImageQualityIndexes = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
AverageShiftedHistograms = "0.8.6"
Distributions = "0.24, 0.25"
ImageQualityIndexes = "0.2, 0.3"
Parameters = "0.12.2"
Plots = "1.20"
Reexport = "1.1"
StatsBase = "0.33.9"
Wavelets = "0.9.3"
julia = "1.5, 1.6"
